services:
  db:
    image: mysql:latest
    container_name: db2
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: ecommercedb
      MYSQL_USER: root
      MYSQL_PASSWORD: my_secret_password
    ports:
      - "3307:3306"
    volumes:
      - ecommercedata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma2
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=ecommercedb
      - DB_USERNAME=root
      - DB_PASSWORD=my_secret_password
    depends_on:
      - db
volumes:
  ecommercedata: